# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table hospital (
  id                        bigint not null,
  hospital_id               bigint,
  hospital_name             varchar(255),
  latitude                  double,
  longitude                 double,
  street_address            varchar(255),
  explain_med               integer,
  sound_intol               integer,
  nurse_qual                integer,
  bedside_man               integer,
  pain                      integer,
  bathroom                  integer,
  promptness                integer,
  price0                    integer,
  price1                    integer,
  price2                    integer,
  price3                    integer,
  price4                    integer,
  price5                    integer,
  price6                    integer,
  price7                    integer,
  price8                    integer,
  price9                    integer,
  price10                   integer,
  price11                   integer,
  price12                   integer,
  price13                   integer,
  price14                   integer,
  price15                   integer,
  price16                   integer,
  price17                   integer,
  price18                   integer,
  price19                   integer,
  price20                   integer,
  price21                   integer,
  price22                   integer,
  price23                   integer,
  price24                   integer,
  price25                   integer,
  price26                   integer,
  price27                   integer,
  price28                   integer,
  price29                   integer,
  price30                   integer,
  price31                   integer,
  price32                   integer,
  price33                   integer,
  price34                   integer,
  price35                   integer,
  price36                   integer,
  price37                   integer,
  price38                   integer,
  price39                   integer,
  price40                   integer,
  price41                   integer,
  price42                   integer,
  price43                   integer,
  price44                   integer,
  price45                   integer,
  price46                   integer,
  price47                   integer,
  price48                   integer,
  price49                   integer,
  price50                   integer,
  price51                   integer,
  price52                   integer,
  price53                   integer,
  price54                   integer,
  price55                   integer,
  price56                   integer,
  price57                   integer,
  price58                   integer,
  price59                   integer,
  price60                   integer,
  price61                   integer,
  price62                   integer,
  price63                   integer,
  price64                   integer,
  price65                   integer,
  price66                   integer,
  price67                   integer,
  price68                   integer,
  price69                   integer,
  price70                   integer,
  price71                   integer,
  price72                   integer,
  price73                   integer,
  price74                   integer,
  price75                   integer,
  price76                   integer,
  price77                   integer,
  price78                   integer,
  price79                   integer,
  price80                   integer,
  price81                   integer,
  price82                   integer,
  price83                   integer,
  price84                   integer,
  price85                   integer,
  price86                   integer,
  price87                   integer,
  price88                   integer,
  price89                   integer,
  price90                   integer,
  price91                   integer,
  price92                   integer,
  price93                   integer,
  price94                   integer,
  price95                   integer,
  price96                   integer,
  price97                   integer,
  price98                   integer,
  price99                   integer,
  constraint pk_hospital primary key (id))
;

create sequence hospital_seq;




# --- !Downs

SET REFERENTIAL_INTEGRITY FALSE;

drop table if exists hospital;

SET REFERENTIAL_INTEGRITY TRUE;

drop sequence if exists hospital_seq;

